# Comparison of Toric Surface Code and BB Code using PanQEC

In [230]:
import sys
from pathlib import Path

from panqec.codes import Toric2DCode
from panqec.error_models import PauliErrorModel

sys.path.append(str(Path("..").resolve()))
from src.BBcode_classes import BBcode_A312_B312
from src.decoder_classes import BeliefPropagationLSDDecoder
from src.errormodel_classes import GaussianPauliErrorModel

## Quantum Storage

In [231]:
# Initializing codes, error model, decoder
toric_code = Toric2DCode(6)
bb_code = BBcode_A312_B312(6)

error_model = GaussianPauliErrorModel(1/3, 1/3, 1/3)
p = 0.1

toric_decoder = BeliefPropagationLSDDecoder(toric_code, error_model, p)
bb_decoder = BeliefPropagationLSDDecoder(bb_code, error_model, p)

In [232]:
# Generate errors and extract syndrome for toric code
toric_errors = error_model.generate(toric_code, p)
toric_syndrome = toric_code.measure_syndrome(toric_errors)

print("Toric Code Errors:", toric_errors)
print("Toric Code Syndrome:", toric_errors)

Toric Code Errors: [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Toric Code Syndrome: [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [233]:
# Generate errors and extract syndrome for BB code
bb_errors = error_model.generate(bb_code, p)
bb_syndrome = bb_code.measure_syndrome(bb_errors)

print("BB Code Errors:", bb_errors)
print("BB Code Syndrome:", bb_errors)

BB Code Errors: [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
BB Code Syndrome: [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]


In [234]:
# Decode syndrome and assert success for toric code correction
toric_correction = toric_decoder.decode(toric_syndrome)
print("Toric Code Correction:", toric_correction)

toric_residual_error = (toric_correction + toric_errors) % 2
print("Toric Code Residual Error:", toric_residual_error)

toric_in_codespace = toric_code.in_codespace(toric_residual_error)
print("Is in codespace:", toric_in_codespace)

toric_logical_errors = toric_code.logical_errors(toric_residual_error)
print("Toric Code Logical Errors:", toric_logical_errors)

toric_success = not toric_code.is_logical_error(toric_residual_error) and toric_in_codespace
print("Success:", toric_success)

Toric Code Correction: [0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Toric Code Residual Error: [0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Is in codespace: True
Toric Code Logical Errors: [0 1 0 0]
Success: False


In [235]:
# Decode syndrome and assert success for BB code correction
bb_correction = bb_decoder.decode(bb_syndrome)
print("BB Code Correction:", bb_correction)

bb_residual_error = (bb_correction + bb_errors) % 2
print("BB Code Residual Error:", bb_residual_error)

bb_in_codespace = bb_code.in_codespace(bb_residual_error)
print("Is in codespace:", bb_in_codespace)

bb_logical_errors = bb_code.logical_errors(bb_residual_error)
print("BB Code Logical Errors:", bb_logical_errors)

bb_success = not bb_code.is_logical_error(bb_residual_error) and bb_in_codespace
print("Success:", bb_success)

BB Code Correction: [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0]
BB Code Residual Error: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Is in codespace: True
BB Code Logical Errors: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Success: True


In [236]:
# Extracting properties:

print(f"Toric code [[n,k,d]]=[[{toric_code.n},{toric_code.k},{toric_code.d}]]")
print(f"BB code [[n,k,d]]=[[{bb_code.n},{bb_code.k},{bb_code.d}]]")

Toric code [[n,k,d]]=[[72,2,6]]
BB code [[n,k,d]]=[[72,12,6]]


## Logical X, Logical Z and Hadamard Gates

In [237]:
# Identifying logicals (toric code)

print("Logicals X (Toric code)", toric_code.logicals_x)
print("Logicals Z (Toric code)", toric_code.logicals_z)

Logicals X (Toric code) [[1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
Logicals Z (Toric code) [[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [238]:
# Identifying logicals (BB code)

print("Logicals X (BB code)", bb_code.logicals_x)
print("Logicals Z (BB code)", bb_code.logicals_z)

Logicals X (BB code) [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]]
Logicals Z (BB code) [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## Applying Logical Gates

In PanQEC, quantum states and operators use **binary symplectic format**:
- State vector has length `2n` (where `n` = number of physical qubits)
- First `n` elements represent X errors/operations
- Last `n` elements represent Z errors/operations
- Gates are applied by adding vectors mod 2

In [240]:
# Example 1: Initialize and apply logical X gate
import numpy as np

# Get the toric code logical operators
print("Toric Code has", toric_code.k, "logical qubits")
print("Logical X operators shape:", toric_code.logicals_x.shape)
print("Logical Z operators shape:", toric_code.logicals_z.shape)

# Initialize logical state |00⟩ (no errors)
logical_state = np.zeros(2*toric_code.n, dtype='uint8')
print("\nInitial logical state |00⟩:")
print("  State vector:", logical_state)
print("  Logical errors:", toric_code.logical_errors(logical_state))

# Apply logical X gate to first qubit: |00⟩ → |10⟩
logical_state_10 = (logical_state + toric_code.logicals_x[0]) % 2
print("\nAfter applying logical X[0], state is |10⟩:")
print("  Logical errors:", toric_code.logical_errors(logical_state_10))
print("  (First X logical anticommutes, so logical_errors[0] = 1)")

# Apply logical Z gate to first qubit: |10⟩ → |10⟩ (Z flips phase, not basis)
logical_state_10_phase = (logical_state_10 + toric_code.logicals_z[0]) % 2
print("\nAfter applying logical Z[0] (phase flip):")
print("  Logical errors:", toric_code.logical_errors(logical_state_10_phase))
print("  (Both X[0] and Z[0] anticommute, so errors are [1,0,1,0])")

Toric Code has 2 logical qubits
Logical X operators shape: (2, 144)
Logical Z operators shape: (2, 144)

Initial logical state |00⟩:
  State vector: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
  Logical errors: [0 0 0 0]

After applying logical X[0], state is |10⟩:
  Logical errors: [1 0 0 0]
  (First X logical anticommutes, so logical_errors[0] = 1)

After applying logical Z[0] (phase flip):
  Logical errors: [1 0 1 0]
  (Both X[0] and Z[0] anticommute, so errors are [1,0,1,0])


In [241]:
# Example 2: Apply logical gates at specific physical locations
# Logical operators define which physical qubits to act on

# View which physical qubits are involved in logical X[0]
log_x0 = toric_code.logicals_x[0]
x_part = log_x0[:toric_code.n]  # First half = X operations
z_part = log_x0[toric_code.n:]  # Second half = Z operations

print("Logical X[0] operator:")
print(f"  Applies X gates at physical qubits: {np.where(x_part == 1)[0]}")
print(f"  Applies Z gates at physical qubits: {np.where(z_part == 1)[0]}")

# Visualize on the grid (for toric code)
x_coords = [toric_code.qubit_coordinates[i] for i in np.where(x_part == 1)[0]]
print(f"  Physical coordinates for X gates: {x_coords}")

Logical X[0] operator:
  Applies X gates at physical qubits: [ 0  6 12 18 24 30]
  Applies Z gates at physical qubits: []
  Physical coordinates for X gates: [(1, 0), (3, 0), (5, 0), (7, 0), (9, 0), (11, 0)]


In [242]:
# Example 3: Create custom logical operations
# You can construct arbitrary Pauli operators by setting bits in binary symplectic format

def apply_physical_gate(state, gate_type, qubit_indices, code):
    """
    Apply physical Pauli gates to specific qubits
    
    Args:
        state: Current state in binary symplectic format (length 2n)
        gate_type: 'X', 'Y', or 'Z'
        qubit_indices: List of physical qubit indices to apply gate to
        code: The quantum error correcting code
    
    Returns:
        New state after applying gates
    """
    new_state = state.copy()
    n = code.n
    
    for idx in qubit_indices:
        if gate_type == 'X':
            new_state[idx] = (new_state[idx] + 1) % 2
        elif gate_type == 'Z':
            new_state[n + idx] = (new_state[n + idx] + 1) % 2
        elif gate_type == 'Y':
            # Y = iXZ in terms of errors
            new_state[idx] = (new_state[idx] + 1) % 2
            new_state[n + idx] = (new_state[n + idx] + 1) % 2
    
    return new_state

# Test: Apply X gates to specific physical qubits
state = np.zeros(2*toric_code.n, dtype='uint8')
print("Initial state:", toric_code.logical_errors(state))

# Apply X gate to physical qubit 5
state = apply_physical_gate(state, 'X', [5], toric_code)
print(f"After X on qubit 5:", toric_code.logical_errors(state))

# Apply Z gate to physical qubit 10
state = apply_physical_gate(state, 'Z', [10], toric_code)
print(f"After Z on qubit 10:", toric_code.logical_errors(state))

# Check if state is still in codespace
print(f"In codespace: {toric_code.in_codespace(state)}")

Initial state: [0 0 0 0]
After X on qubit 5: [1 0 0 0]
After Z on qubit 10: [1 0 0 0]
In codespace: False


In [243]:
# Example 4: Complete workflow - Initialize, apply logical gates, add errors, decode
print("=== Complete Quantum Memory Workflow ===\n")

# 1. Initialize in logical state |00⟩
logical_state = np.zeros(2*toric_code.n, dtype='uint8')
print("1. Initial logical state |00⟩")
print(f"   Logical errors: {toric_code.logical_errors(logical_state)}")

# 2. Apply logical X gate to first qubit: |00⟩ → |10⟩
logical_state = (logical_state + toric_code.logicals_x[0]) % 2
print("\n2. Applied logical X[0]: |00⟩ → |10⟩")
print(f"   Logical errors: {toric_code.logical_errors(logical_state)}")

# 3. Add some physical noise
noise = error_model.generate(toric_code, p)
noisy_state = (logical_state + noise) % 2
print(f"\n3. Added physical noise (p={p})")
print(f"   Noisy logical errors: {toric_code.logical_errors(noisy_state)}")
print(f"   In codespace: {toric_code.in_codespace(noisy_state)}")

# 4. Measure syndrome and decode
syndrome = toric_code.measure_syndrome(noisy_state)
correction = toric_decoder.decode(syndrome)
corrected_state = (noisy_state + correction) % 2
print(f"\n4. After error correction:")
print(f"   Corrected logical errors: {toric_code.logical_errors(corrected_state)}")
print(f"   In codespace: {toric_code.in_codespace(corrected_state)}")

# 5. Check if we recovered the correct logical state
success = np.array_equal(toric_code.logical_errors(corrected_state), 
                         toric_code.logical_errors(logical_state))
print(f"\n5. Successfully preserved logical state |10⟩: {success}")

=== Complete Quantum Memory Workflow ===

1. Initial logical state |00⟩
   Logical errors: [0 0 0 0]

2. Applied logical X[0]: |00⟩ → |10⟩
   Logical errors: [1 0 0 0]

3. Added physical noise (p=0.1)
   Noisy logical errors: [1 0 0 0]
   In codespace: False

4. After error correction:
   Corrected logical errors: [1 0 0 0]
   In codespace: True

5. Successfully preserved logical state |10⟩: True


In [244]:
# Example 5: Same workflow with BB code (requires code with logical qubits!)
# First, create a BB code with non-zero logical qubits
bb_code_working = BBcode_A312_B312(6)  # 6x6 has 12 logical qubits
bb_decoder_working = BeliefPropagationLSDDecoder(bb_code_working, error_model, p)

print(f"=== BB Code Workflow (size 6x6, k={bb_code_working.num_logical_qubits} logical qubits) ===\n")

# Initialize in |0...0⟩
bb_state = np.zeros(2*bb_code_working.n, dtype='uint8')
print(f"1. Initial state |0...0⟩:")
print(f"   Logical errors (first 8): {bb_code_working.logical_errors(bb_state)[:8]}")

# Apply logical X gate to first logical qubit
bb_state = (bb_state + bb_code_working.logicals_x[0]) % 2
print(f"\n2. After applying logical X[0]:")
print(f"   Logical errors (first 8): {bb_code_working.logical_errors(bb_state)[:8]}")

# Add noise and correct
bb_noise = error_model.generate(bb_code_working, p)
bb_noisy = (bb_state + bb_noise) % 2
bb_syndrome = bb_code_working.measure_syndrome(bb_noisy)
bb_correction = bb_decoder_working.decode(bb_syndrome)
bb_corrected = (bb_noisy + bb_correction) % 2

print(f"\n3. After noise and correction:")
print(f"   Logical errors (first 8): {bb_code_working.logical_errors(bb_corrected)[:8]}")
print(f"   Successfully preserved logical state: {np.array_equal(bb_code_working.logical_errors(bb_corrected), bb_code_working.logical_errors(bb_state))}")

=== BB Code Workflow (size 6x6, k=12 logical qubits) ===

1. Initial state |0...0⟩:
   Logical errors (first 8): [0 0 0 0 0 0 0 0]

2. After applying logical X[0]:
   Logical errors (first 8): [1 0 1 0 0 1 0 1]

3. After noise and correction:
   Logical errors (first 8): [1 0 1 0 0 1 0 1]
   Successfully preserved logical state: True


## Summary: How to Apply Logical Gates

### Key Concepts

1. **Binary Symplectic Format**: States are represented as length-`2n` vectors where:
   - Elements `[0:n]` = X errors/operations on physical qubits
   - Elements `[n:2n]` = Z errors/operations on physical qubits

2. **Logical Operators**: Access via `code.logicals_x` and `code.logicals_z`
   - Shape: `(k, 2n)` where `k` = number of logical qubits
   - Each row is a logical operator in binary symplectic format

3. **Applying Gates**: Use modulo-2 addition
   ```python
   new_state = (old_state + logical_operator) % 2
   ```

4. **Physical Gate Application**: 
   - For X gate on qubit i: flip bit at index `i`
   - For Z gate on qubit i: flip bit at index `n+i`
   - For Y gate on qubit i: flip both bits

5. **Checking State**:
   - `code.logical_errors(state)` - returns length-`2k` array showing which logical operators anticommute
   - `code.in_codespace(state)` - True if syndrome is zero
   - `code.is_logical_error(state)` - True if any logical operator anticommutes

### Workflow
1. Initialize state (e.g., `np.zeros(2*code.n)` for |0...0⟩)
2. Apply logical gates by adding logical operators
3. Add noise if simulating errors
4. Measure syndrome and decode
5. Check if logical state preserved